apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-web-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sample-web-app
        version: "v1.0.5"
    spec:
      containers:
        - name: sample-web-app
          image: 'duttasayan666/sampleweb:1.0.5.RELEASE'
          ports:
            - containerPort: 8080
          resources:
              limits:
                memory: 256Mi
                cpu: "0.2"